### ISSUE TITLE
Fix edit option showing for non members

### ISSUE THREAD

**Issue by mcnaveen** [mcnaveen/liny#9]
### Describe the Bug

It should show only for OWNER, ADMIN, MEMBER roles

**Comment by MuruganandamVG** [comment]
I will work on this @mcnaveen

**Comment by mcnaveen** [comment]
Hi @MuruganandamVG Thank you. I think the entire menu can be hidden for the non-members. 
There is a helper function here. https://github.com/mcnaveen/liny/blob/dev/helpers/common/hasAccess.ts

Which can determine whether the current user has access to the resource or not. Based on that, you can hide/show the menu.

Examples: https://github.com/search?q=repo%3Amcnaveen/liny%20checkUserAccess&type=code

![GszR1foloEfJCRkv000008](https://github.com/user-attachments/assets/a7b459eb-ccba-45bf-8e0a-26b58200780e)

> Send PR to `dev` branch

Please let me know if you need any more help.

**Comment by MuruganandamVG** [comment]
Hi @mcnaveen  Could you pls share the env variables

**Comment by mcnaveen** [comment]
What env variables? You can generate yourself.

**Comment by MuruganandamVG** [comment]
Google,Github client Id and secret . Ok got it I can generate this with my account

**Comment by mcnaveen** [comment]
Generate either GitHub or Google. It's just for authentication. [For the secret check here](https://acte.ltd/utils/randomkeygen).

Please check [.env.example](https://github.com/mcnaveen/liny/blob/dev/.env.example)

**Comment by mcnaveen** [comment]
Also, Please check Contribution Guidelines at https://github.com/mcnaveen/liny/blob/dev/docs/CONTRIBUTING.md#development-workflow
